#!/usr/bin/bash

# Colors as per: http://www.tldp.org/LDP/abs/html/colorizing.html

echoerrcolor() {
	if (( $colors )); then
		case $1 in
			none)
				str="\e[0;37m"
				;;
			green)
				str="\e[0;32m"
				;;
			red)
				str="\e[0;31m"
				;;
			blue)
				str="\e[1;34m"
				;;
			darkcyan)
				str="\e[0;36m"
				;;
			darkgreen)
				str="\e[1;32m"
				;;
			darkred)
				str="\e[1;31m"
				;;
			magenta)
				str="\e[0;35m"
				;;
			darkmagenta)
				str="\e[1;35m"
				;;

		esac
		echo -ne $str >&2;
	fi
}

echoerrnocolor() {
	if (( $colors )); then
		echo -ne "\e[0m" >&2;
	fi
}

echoerr() { 
	if [ $# -gt 1 ]; then
		color=$1
		shift
		echoerrcolor $color
	fi
	echo "$@" >&2;
	if [ $color ]; then
		echoerrnocolor
	fi
}

printferr() { printf "$@" >&2; }

$(which git >& /dev/null)

if [ $? -eq 1 ]; then
	echoerr red "Git not found! Confirm it is indeed installed and reachable."
	exit;
fi

appendshell() {
    echo 'appendshell(): called...'
}

testmode=0;
verboseconf=0;
dumpconf=0;
preview=1;
colors=0;

while [ $# -ne 0 ]; do
	case "$1" in
		test)
			testmode=1;
			echoerr darkcyan "Test mode enabled."
			;;
		no-test)
			testmode=0;
			echoerr darkcyan "Test mode disabled."
			;;
		verbose-config)
			verboseconf=1;
			echoerr darkcyan "Verbose configuration file active."
			;;
		no-verbose-config)
			verboseconf=0;
			echoerr darkcyan "Concise configuration file active."
			;;
		dump-config)
			dumpconf=1;
			echoerr darkcyan "Will dump config to stdout."
			;;
		no-dump-config)
			dumpconf=0;
			echoerr darkcyan "Will not dump config to stdout."
			;;
		preview)
			preview=1;
			echoerr darkcyan "Will show commands to be executed."
			;;
		no-preview)
			preview=0;
			echoerr darkcyan "Will not show commands to be executed."
			;;
		colors)
			colors=1;
			echoerr darkcyan "Will print with colors."
			;;
		no-colors)
			colors=0;
			echoerr darkcyan "No color."
			;;
		*)
			echoerr red "Unfamiliar configuration option"
	esac
	shift
done

echo 'init started...'
